parameters:
  notifier.class: Notifier\Notifier
  notifier.channel_resolver.class: Notifier\NotifierBundle\Notifier\ChannelResolver
  notifier.rule_set.class: Notifier\NotifierBundle\Notifier\RuleSet

services:
  notifier:
    class: "%notifier.class%"
    arguments:
      - "@notifier.channel_resolver"

  notifier.channel_resolver:
    class: "%notifier.channel_resolver.class%"
